const url = window.location.href;

export const lang: 'en' | 'cn' = url.includes('cn') ? 'cn' : 'en';

export const langConfig = {
    'en': {
        "panel": {
            "case": "Case:",
            "undo": "Undo",
            "redo": "Redo",
            "run": "Run",
            "autoRun": "AutoRun",
            "autoRunTitle": "Set whether to automatically run code upon changes",
            "spec": "Specification",
            "specTitle": "The mapping specification that transforms the input table to the output table",
            "matchedInst": "Matched Instances",
            "matchedInstTitle": "A tree data structure that contains the AreaInfo of all matched instances, starting from the root area",
        },
        "pattern": {
            "patterns": "Mapping Patterns",
            "currentInst": "Current instance:",
            "match": "Match:",
            "region": "Region",
            "regionTitle": "Click to select a starting area in the input table. Press 'Esc' to cancel the selection mode.",
            "extract": "Extract by:",
            "position": "Position",
            "positionTitle": "Click to select a starting area in the input table for matching and extracting by position. Press 'Esc' to cancel the selection mode.",
            "context": "Context",
            "contextTitle": "Click to select a starting area in the input table for matching and extracting by context. Press 'Esc' to cancel the selection mode.",
            "value": "Value",
            "valueTitle": "Click to select a starting area in the input table for matching and extracting by value. Press 'Esc' to cancel the selection mode.",
            "reset": "Reset View",
            "previousInst": "Previous instance",
            "nextInst": "Next instance",
            "selectionMode": "Press ESC to cancel the selection mode.",
            "addConstr": "Please select the constrained cell in the input table.",
            "addSubPattern": "Please select an area in the input table.",
        },
        "table": {
            "input": "Input Table",
            "upload": "Upload",
            "reset": "Reset Data",
            "output": "Output Table",
            "download": "Download",
        },
        "store": {
            "for": "For the",
            "template": "template,",
            "matched": "instances are matched.",
            "oneMatch": "only one instance is matched.",
            "noMatch": "no instance is matched.",
            "emptyTable": "The output table is empty based on the specification.",
            "failedTransform": "Failed to transform the table based on the specification:",
            "failedParse": "Failed to parse the specification:",
            "invalidPath": "The node path is invalid.",
            "invalidInstNum": "The input number is out of range: ",
            "menu": {
                "addPattern": "Add Sub-Pattern",
                "position": "Position",
                "positionTitle": "Match and Extract by Position",
                "context": "Context",
                "contextTitle": "Match and Extract by Context",
                "value": "Value",
                "valueTitle": "Match and Extract by Value",
                "region": "Region",
                "regionTitle": "Match Without Extraction",
                "addConstr": "Add Constraint",
                "resetCol": "Reset Target Cols",
                "resetColTitle": "Reset the Match & Extract Method of the Target Cols",
                "deletePattern": "Delete This Pattern",
                "deletePatternTitle": "Delete This Pattern.\nShortcut: Delete/Backspace",
                "deleteConstr": "Delete This Constraint",
                "deleteConstrTitle": "Delete This Constraint.\nShortcut: Delete/Backspace",
            }
        },
        "tree": {
            "function": "The cell is constrained by a custom function:\nClick to see details in the Code Panel.",
            "string": "The cell's data type should be a string.",
            "number": "The cell's data type should be a number.",
            "none": "The cell should be an empty string, null, or undefined.",
            "notNone": "The cell should not be an empty string, null, or undefined.",
            "equal": "The cell should be ",
            "width": "Width: ",
            "height": "Height: ",
            "path": "Pattern Path: ",
            "noMatch": "Don't match any instances",
            "matched": "Match: ",
            "instances": "instances",
            "total": "Total ",
        },
        "others": {
            "colType": "cell(s) with a data type of",
            "string": "string",
            "number": "number",
            "none": "none",
            "targetCol": "The cell's Target Column is:",
            "noTargetCol": "No Target Column"
        }
    },
    'cn': {
        "panel": {
            "case": "演示案例 :",
            "undo": "撤销",
            "redo": "重做",
            "run": "运行",
            "autoRun": "自动运行",
            "autoRunTitle": "设置是否在代码改变时自动运行代码",
            "spec": "映射规范",
            "specTitle": "将输入表转换为输出表的语义映射规范",
            "matchedInst": "匹配实例",
            "matchedInstTitle": "从根区域开始，包含所有匹配实例的AreaInfo的树数据结构",
        },
        "pattern": {
            "patterns": "映射模式",
            "currentInst": "当前实例 :",
            "match": "匹配方式 :",
            "region": "区域",
            "regionTitle": "点击选择输入表中的起始区域。按ESC键取消选择模式。",
            "extract": "抽取方式 :",
            "position": "位置",
            "positionTitle": "点击选择输入表中的起始区域以进行位置匹配和抽取。按ESC键取消选择模式。",
            "context": "上下文",
            "contextTitle": "点击选择输入表中的起始区域以进行上下文匹配和抽取。按ESC键取消选择模式。",
            "value": "值",
            "valueTitle": "点击选择输入表中的起始区域以进行值匹配和抽取。按ESC键取消选择模式。",
            "reset": "重置视图",
            "previousInst": "上一个实例",
            "nextInst": "下一个实例",
            "selectionMode": "按ESC键取消选择模式。",
            "addConstr": "请在输入表中选择约束单元格。",
            "addSubPattern": "请在输入表中选择子模式单元格区域。",
        },
        "table": {
            "input": "输入表",
            "upload": "上传",
            "reset": "重置数据",
            "output": "输出表",
            "download": "下载",
        },
        "store": {
            "for": "对于第",
            "template": "模板，",
            "matched": "个实例匹配成功。",
            "oneMatch": "只有一个实例匹配成功。",
            "noMatch": "没有实例匹配成功。",
            "emptyTable": "输出表为空，基于规范匹配成功。",
            "failedTransform": "基于规范重构表格失败，原因为:",
            "failedParse": "解析规范失败，原因为:",
            "invalidPath": "该节点路径无效。",
            "invalidInstNum": "输入的实例数值超出范围：",
            "menu": {
                "addPattern": "添加子模式",
                "position": "位置",
                "positionTitle": "按位置匹配和抽取",
                "context": "上下文",
                "contextTitle": "按上下文匹配和抽取",
                "value": "值",
                "valueTitle": "按值匹配和抽取",
                "region": "区域",
                "regionTitle": "不抽取",
                "addConstr": "添加约束",
                "resetCol": "重置目标列",
                "resetColTitle": "重置目标列的匹配和抽取方式",
                "deletePattern": "删除此模式",
                "deletePatternTitle": "删除此模式。\n快捷键：Delete/Backspace",
                "deleteConstr": "删除此约束",
                "deleteConstrTitle": "删除此约束。\n快捷键：Delete/Backspace",
            }
        },
        "tree": {
            "function": "该单元格受自定义函数约束：\n点击“代码面板”查看详细信息。",
            "string": "该单元格的数据类型应为字符串。",
            "number": "该单元格的数据类型应为数值。",
            "none": "该单元格应为空字符串，null，或undefined。",
            "notNone": "该单元格不应为空字符串，null，或undefined。",
            "equal": "该单元格应为：",
            "width": "宽：",
            "height": "高：",
            "path": "模式路径：",
            "noMatch": "没有匹配任何实例",
            "matched": "匹配：",
            "instances": "个实例",
            "total": "总共匹配了",
        },
        "others": {
            "colType": "个单元格的数据类型为",
            "string": "字符串 (string)",
            "number": "数值 (number)",
            "none": "空 (none)",
            "targetCol": "该单元格在输出表中的映射目标列为：",
            "noTargetCol": "该单元格在输出表中无映射目标列"
        }
    }
}